<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\FirstCry\src\FirstCry.Infrastructure\FirstCry.Infrastructure.csproj" />
    <ProjectReference Include="..\..\backend\FirstCry\src\FirstCry.Domain\FirstCry.Domain.csproj" />
  </ItemGroup>

</Project>
